### ISSUE TITLE
Persistent Accounts

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#244]
Tasks:
- [x] https://github.com/kamu-data/kamu-node/issues/52
- [x] https://github.com/kamu-data/kamu-node/issues/68
- [x] https://github.com/kamu-data/kamu-cli/issues/645
- [x] #540 
- [x] https://github.com/kamu-data/kamu-cli/issues/566

**Comment by sergiimk** [comment]
@zaychenko-sergei can this epic be closed?
