### ISSUE TITLE
ARM / Mac Support

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#246]
Now that github [finally supports M]-series](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/) runners we should provide full support for `arm64` architecture on linux and macos. 

Supporting this architecture on Linux would allow us to run our AWS deployments on Graviton ARM processors.

Tasks:
- [x] Multi-arch image for `kamu-engine-datafusion`
- [x] Multi-arch image for `kamu-engine-spark`
  - [x] Blocked by: https://github.com/kamu-data/kamu-engine-spark/issues/4 as `bitnami/spark` images have `arm64` architecture only starting from `v3.2.3`
- [x] Multi-arch image for `kamu-engine-flink`
- [x] Multi-arch image for `jupyter`
- [x] Multi-arch image for `demo`
- [ ] Multi-arch developer images (decided to skip, since there is no strict necessity yet)
- [x] Support `arm64` linux and darwin targets in `kamu-cli` release build
- [x] Test installers for all targets
- [x] Test on AWS Graviton
- [ ] Update docs
- [ ] Announce on Discord
