### ISSUE TITLE
Python client and Jupyter integration

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#553]
### RFC
https://docs.google.com/document/d/1y6BC10HJ7unC9oAMVVDXPUy86AzUI7MPKIWloc8DQiU/edit?tab=t.0

### Implementation
- [x] New [`kamu-client-python`](https://github.com/kamu-data/kamu-client-python) library
- [x] https://github.com/kamu-data/kamu-cli/pull/1012
- [x] https://github.com/kamu-data/kamu-node/pull/176
- [x] https://github.com/kamu-data/kamu-docs/pull/29
- [x] https://github.com/kamu-data/kamu-contrib/pull/27

### Test Plan
https://github.com/kamu-data/kamu-testing/pull/1
