### ISSUE TITLE
Tracking issue: Partially incorrect links in Get Data panel

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#579]
This is a tracking issue to fix inaccuracies in the links provided for Get Data panel

# Steps

- [ ] kamu-cli: https://github.com/kamu-data/kamu-cli/issues/577
- [ ] kamu-node: https://github.com/kamu-data/kamu-node/pull/69
- [ ] helm-charts: TBA
- [ ] kamu-deploy: TBA

**Comment by s373r** [comment]
Merged into the ticket: https://github.com/kamu-data/kamu-cli/issues/577
