### ISSUE TITLE
Tracking issue: Reinforce E2E test coverage

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#895]
- [x] https://github.com/kamu-data/kamu-cli/issues/877
  - [x] https://github.com/kamu-data/kamu-cli/issues/932
  - [x] https://github.com/kamu-data/kamu-cli/pull/935
- [x] https://github.com/kamu-data/kamu-cli/issues/898
- [x] https://github.com/kamu-data/kamu-cli/issues/896
- [x] https://github.com/kamu-data/kamu-cli/issues/897
